# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
trigger:
  branches:
    include:
    - master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    fetchTags: true
  - task: PowerShell@2
    displayName: PowerShell Script
    enabled: False
    inputs:
      filePath: .
      arguments: ls -la
  - task: DeleteFiles@1
    displayName: Delete old zip files
    enabled: False
    inputs:
      Contents: '*.zip'
  - task: DownloadSecureFile@1
    displayName: Download secure file
    inputs:
      secureFile: 9706d656-f5d6-4fff-b80e-d1ffcb8597a3
      retryCount: 5
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: src
      verbose: false
  - task: CopyFiles@2
    displayName: Copy Config File
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: .env.production
      TargetFolder: src/
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: run build
  - task: ArchiveFiles@1
    displayName: Archive src/build
    inputs:
      rootFolder: build
      archiveType: zip
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
